// data from https://www.kingarthurbaking.com/learn/ingredient-weight-chart

const DATA = [
  {
    ingredient: "'00' Pizza Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 116,
  },
  {
    ingredient: "Agave syrup",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 3,
    gram: 84,
  },
  {
    ingredient: "All-Purpose Baking Mix",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "All-Purpose Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Almond butter",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 2.3333333333333335,
    gram: 68,
  },
  {
    ingredient: "Almond Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.375,
    gram: 96,
  },
  {
    ingredient: "Almond meal",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3,
    gram: 84,
  },
  {
    ingredient: "Almond paste (packed)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 9.125,
    gram: 259,
  },
  {
    ingredient: "Almonds (sliced)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.5,
    gram: 43,
  },
  {
    ingredient: "Almonds (slivered)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Almonds, whole (unblanched)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Amaranth flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.625,
    gram: 103,
  },
  {
    ingredient: "Apple juice concentrate",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 70,
  },
  {
    ingredient: "Apples (dried, diced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Apples (peeled, sliced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Applesauce",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 9,
    gram: 255,
  },
  {
    ingredient: "Apricots (dried, diced)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.25,
    gram: 64,
  },
  {
    ingredient: "Artisan Bread Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Artisan Bread Topping",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.5,
    gram: 43,
  },
  {
    ingredient: "Baker's Cinnamon Filling",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.375,
    gram: 152,
  },
  {
    ingredient: "Baker's Fruit Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.5,
    gram: 128,
  },
  {
    ingredient: "Baker's Special Sugar (superfine sugar, castor sugar)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6.75,
    gram: 190,
  },
  {
    ingredient: "Baking powder",
    volume: "1 teaspoon",
    volumeRaw: 1,
    volumeUnit: "teaspoon",
    ounce: 0.125,
    gram: 4,
  },
  {
    ingredient: "Baking soda",
    volume: "1/2 teaspoon",
    volumeRaw: 0.5,
    volumeUnit: "teaspoon",
    ounce: 0.1,
    gram: 3,
  },
  {
    ingredient: "Baking Sugar Alternative",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Bananas (mashed)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Barley (cooked)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 7.625,
    gram: 215,
  },
  {
    ingredient: "Barley (pearled)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 7.5,
    gram: 213,
  },
  {
    ingredient: "Barley flakes",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.625,
    gram: 46,
  },
  {
    ingredient: "Barley flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Barley malt syrup",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 1.5,
    gram: 42,
  },
  {
    ingredient: "Basil pesto",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Bell peppers (fresh)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Berries (frozen)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Better Cheddar Cheese Powder",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Blueberries (dried)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.5,
    gram: 156,
  },
  {
    ingredient: "Blueberries (fresh or frozen)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: [5, 6],
    gram: [140, 170],
  },
  {
    ingredient: "Blueberry juice",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8.5,
    gram: 241,
  },
  {
    ingredient: "Boiled cider",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Bran cereal",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 2.125,
    gram: 60,
  },
  {
    ingredient: "Bread Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Breadcrumbs (dried)",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Breadcrumbs (fresh)",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 0.75,
    gram: 21,
  },
  {
    ingredient: "Breadcrumbs (Japanese Panko)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 1.75,
    gram: 50,
  },
  {
    ingredient: "Brown rice (cooked)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Brown rice flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.5,
    gram: 128,
  },
  {
    ingredient: "Brown sugar (dark or light, packed)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 7.5,
    gram: 213,
  },
  {
    ingredient: "Buckwheat (whole)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Buckwheat Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Bulgur",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.375,
    gram: 152,
  },
  {
    ingredient: "Butter",
    volume: "8 tablespoons (1/2 cup)",
    volumeRaw: 8,
    volumeUnit: "tablespoons",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Buttermilk",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Buttermilk Biscuit Flour Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.875,
    gram: 110,
  },
  {
    ingredient: "Buttermilk powder",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.6666666666666666,
    gram: 18,
  },
  {
    ingredient: "Cacao nibs",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Cake Enhancer",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.5,
    gram: 14,
  },
  {
    ingredient: "Candied Lemon Peel",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.3333333333333333,
    gram: 37,
  },
  {
    ingredient: "Candied Orange Peel",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 0.875,
    gram: 25,
  },
  {
    ingredient: 'Caramel (14-16 individual pieces, 1" squares)',
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Caramel bits (chopped Heath or toffee)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.5,
    gram: 156,
  },
  {
    ingredient: "Caraway seeds",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.625,
    gram: 18,
  },
  {
    ingredient: "Carrots (cooked and puréed)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4.5,
    gram: 128,
  },
  {
    ingredient: "Carrots (diced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Carrots (grated)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.5,
    gram: 99,
  },
  {
    ingredient: "Cashews (chopped)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Cashews (whole)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Celery (diced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Cheese (Feta)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Cheese (grated cheddar, jack, mozzarella, or Swiss)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Cheese (grated Parmesan)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.75,
    gram: 50,
  },
  {
    ingredient: "Cheese (Ricotta)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Cherries (candied)",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.75,
    gram: 50,
  },
  {
    ingredient: "Cherries (dried)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 71,
  },
  {
    ingredient: "Cherries (fresh, pitted, chopped)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.875,
    gram: 80,
  },
  {
    ingredient: "Cherries (frozen)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Cherry Concentrate",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 1.5,
    gram: 42,
  },
  {
    ingredient: "Chia seeds",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.3333333333333333,
    gram: 37,
  },
  {
    ingredient: "Chickpea flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Chives (fresh)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 0.75,
    gram: 21,
  },
  {
    ingredient: "Chocolate (chopped)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Chocolate Chips",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Chocolate Chunks",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Chocolate Mousse Mix",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Cinnamon Sweet Bits",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.25,
    gram: 35,
  },
  {
    ingredient: "Cinnamon-Sugar",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.75,
    gram: 50,
  },
  {
    ingredient: "Climate Blend Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 115,
  },
  {
    ingredient: "Cocoa (unsweetened)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.5,
    gram: 42,
  },
  {
    ingredient: "Coconut (sweetened, shredded)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Coconut (toasted)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Coconut (unsweetened, desiccated)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Coconut (unsweetened, large flakes)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 2.125,
    gram: 60,
  },
  {
    ingredient: "Coconut (unsweetened, shredded)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 1.875,
    gram: 53,
  },
  {
    ingredient: "Coconut cream (unsweetened)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 10,
    gram: 284,
  },
  {
    ingredient: "Coconut Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.5,
    gram: 128,
  },
  {
    ingredient: "Coconut milk (evaporated)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8.5,
    gram: 242,
  },
  {
    ingredient: "Coconut Milk Powder",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Coconut milk; canned, well shaken",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8.5,
    gram: 241,
  },
  {
    ingredient: "Coconut oil",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Coconut sugar",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.75,
    gram: 77,
  },
  {
    ingredient: "Confectioners' sugar (unsifted)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Cookie butter",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 72,
  },
  {
    ingredient: "Cookie crumbs",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Corn (fresh or frozen)",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.3333333333333333,
    gram: 38,
  },
  {
    ingredient: "Corn (popped)",
    volume: "4 cups",
    volumeRaw: 4,
    volumeUnit: "cups",
    ounce: 0.75,
    gram: 21,
  },
  {
    ingredient: "Corn syrup",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 11,
    gram: 312,
  },
  {
    ingredient: "Cornmeal (whole)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.875,
    gram: 138,
  },
  {
    ingredient: "Cornmeal (yellow, Quaker)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.5,
    gram: 156,
  },
  {
    ingredient: "Cornstarch",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Cottage cheese",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Cracked wheat",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.25,
    gram: 149,
  },
  {
    ingredient: "Cranberries (dried)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Cranberries (fresh or frozen)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.5,
    gram: 99,
  },
  {
    ingredient: "Cream (heavy cream, light cream, or half & half)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Cream cheese",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Cream of coconut",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Crème fraiche",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Currants",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Dates (chopped)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.25,
    gram: 149,
  },
  {
    ingredient: "Demerara sugar",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 7.75,
    gram: 220,
  },
  {
    ingredient: "Dried Blueberry Powder",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Dried milk (Baker's Special Dry Milk)",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Dried nonfat milk (powdered)",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Dried potato flakes (instant mashed potatoes)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.5,
    gram: 43,
  },
  {
    ingredient: "Dried whole milk (powdered)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.75,
    gram: 50,
  },
  {
    ingredient: "Durum Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.375,
    gram: 124,
  },
  {
    ingredient: "Easy Roll Dough Improver",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.625,
    gram: 18,
  },
  {
    ingredient: "Egg (fresh)",
    volume: "1 large",
    volumeRaw: 1,
    volumeUnit: "large",
    ounce: 1.75,
    gram: 50,
  },
  {
    ingredient: "Egg white (fresh)",
    volume: "1 large",
    volumeRaw: 1,
    volumeUnit: "large",
    ounce: [1, 1.25],
    gram: [30, 35],
  },
  {
    ingredient: "Egg whites (dried)",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.375,
    gram: 11,
  },
  {
    ingredient: "Egg yolk (fresh)",
    volume: "1 large",
    volumeRaw: 1,
    volumeUnit: "large",
    ounce: 0.5,
    gram: 14,
  },
  {
    ingredient: "Espresso Powder",
    volume: "1 tablespoon",
    volumeRaw: 1,
    volumeUnit: "tablespoon",
    ounce: 0.25,
    gram: 7,
  },
  {
    ingredient: "Everything Bagel Topping",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.25,
    gram: 35,
  },
  {
    ingredient: "Figs (dried, chopped)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.25,
    gram: 149,
  },
  {
    ingredient: "First Clear Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 106,
  },
  {
    ingredient: "Flax meal",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.75,
    gram: 50,
  },
  {
    ingredient: "Flaxseed",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.25,
    gram: 35,
  },
  {
    ingredient: "Formaggio Italiano Cheese and Herb Blend",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1,
    gram: 30,
  },
  {
    ingredient: "French-Style Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Fruitcake Fruit Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Garlic (cloves, in skin for roasting)",
    volume: "1 large head",
    volumeRaw: 1,
    volumeUnit: "large",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Garlic (minced)",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Garlic (peeled and sliced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.25,
    gram: 149,
  },
  {
    ingredient: "Ghee",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.5,
    gram: 44,
  },
  {
    ingredient: "Ginger (fresh, sliced)",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Gluten-Free All-Purpose Baking Mix",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Gluten-Free All-Purpose Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.5,
    gram: 156,
  },
  {
    ingredient: "Gluten-Free Bread Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Gluten-Free Measure for Measure Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Gluten-Free Pizza Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.5,
    gram: 100,
  },
  {
    ingredient:
      "Gluten-Free sourdough starter (made with Gluten-Free Bread Flour)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: [6, 6.5],
    gram: [170, 185],
  },
  {
    ingredient:
      "Gluten-Free sourdough starter (made with Gluten-Free Measure for Measure Flour)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: [8, 8.5],
    gram: [227, 241],
  },
  {
    ingredient: "Glutinous rice flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Golden Wheat Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Graham cracker crumbs (store-bought or crushed from whole)",
    volume: "1 cup (6 to 7 crackers)",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.5,
    gram: 100,
  },
  {
    ingredient: "Granola",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Grape Nuts",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Guava paste",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 3.5,
    gram: 100,
  },
  {
    ingredient: "Harvest Grains Blend",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.625,
    gram: 74,
  },
  {
    ingredient: "Hazelnut flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.125,
    gram: 89,
  },
  {
    ingredient: "Hazelnut Praline Paste",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 5.5,
    gram: 156,
  },
  {
    ingredient: "Hazelnut spread",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 5.625,
    gram: 160,
  },
  {
    ingredient: "Hazelnuts (whole)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Hi-Maize Natural Fiber",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.125,
    gram: 32,
  },
  {
    ingredient: "High-Gluten Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Honey",
    volume: "1 tablespoon",
    volumeRaw: 1,
    volumeUnit: "tablespoon",
    ounce: 0.75,
    gram: 21,
  },
  {
    ingredient: "Instant Clearjel",
    volume: "1 tablespoon",
    volumeRaw: 1,
    volumeUnit: "tablespoon",
    ounce: 0.375,
    gram: 11,
  },
  {
    ingredient: "Irish-Style Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.875,
    gram: 110,
  },
  {
    ingredient: "Italian Herb Seasoning",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.5,
    gram: 14,
  },
  {
    ingredient: "Italian-Style Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 106,
  },
  {
    ingredient: "Jam or preserves",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Jammy Bits",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6.5,
    gram: 184,
  },
  {
    ingredient: "Keto Wheat Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Keto Wheat Pizza Crust Mix",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.875,
    gram: 110,
  },
  {
    ingredient: "Key Lime Juice",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Lard",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Leeks (diced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.25,
    gram: 92,
  },
  {
    ingredient: "Lemon Crumbles",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6.333333333333333,
    gram: 180,
  },
  {
    ingredient: "Lemon Curd",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Lemon juice",
    volume: "1 tablespoon",
    volumeRaw: 1,
    volumeUnit: "tablespoon",
    ounce: 0.5,
    gram: 14,
  },
  {
    ingredient: "Lemon Juice Powder",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.625,
    gram: 18,
  },
  {
    ingredient: "Lime Juice Powder",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.625,
    gram: 18,
  },
  {
    ingredient: "Macadamia nuts (whole)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.25,
    gram: 149,
  },
  {
    ingredient: "Malt syrup",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 1.5,
    gram: 43,
  },
  {
    ingredient: "Malted Milk Powder",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.25,
    gram: 35,
  },
  {
    ingredient: "Malted Wheat Flakes",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.25,
    gram: 64,
  },
  {
    ingredient: "Maple Cinnamon French Toast Sugar",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.6666666666666665,
    gram: 48,
  },
  {
    ingredient: "Maple Cream",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 1.5,
    gram: 42,
  },
  {
    ingredient: "Maple sugar",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.75,
    gram: 78,
  },
  {
    ingredient: "Maple syrup",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 5.5,
    gram: 156,
  },
  {
    ingredient: "Marshmallow Fluff®",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.5,
    gram: 128,
  },
  {
    ingredient: "Marshmallow spread, homemade",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 72,
  },
  {
    ingredient: "Marshmallow spread, store-bought",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.333333333333333,
    gram: 123,
  },
  {
    ingredient: "Marshmallows (mini)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 1.5,
    gram: 43,
  },
  {
    ingredient: "Marzipan",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 10.125,
    gram: 290,
  },
  {
    ingredient: "Masa Harina",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.25,
    gram: 93,
  },
  {
    ingredient: "Mascarpone cheese",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Mashed potatoes",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 7.5,
    gram: 213,
  },
  {
    ingredient: "Mashed sweet potatoes",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8.5,
    gram: 240,
  },
  {
    ingredient: "Matcha powder",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.375,
    gram: 12,
  },
  {
    ingredient: "Mayonnaise",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Medium Rye Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 106,
  },
  {
    ingredient: "Meringue powder",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.5,
    gram: 43,
  },
  {
    ingredient: "Milk (evaporated)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Milk (fresh)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Millet (whole)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 3.625,
    gram: 103,
  },
  {
    ingredient: "Mini chocolate chips",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6.25,
    gram: 177,
  },
  {
    ingredient: "Mini Diced Ginger",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 73,
  },
  {
    ingredient: "Molasses",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Mushrooms (sliced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 2.75,
    gram: 78,
  },
  {
    ingredient: "Non-Diastatic Malt Powder",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.625,
    gram: 18,
  },
  {
    ingredient: "Nutella",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 5.25,
    gram: 149,
  },
  {
    ingredient: "Oat bran",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.875,
    gram: 53,
  },
  {
    ingredient: "Oat Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.25,
    gram: 92,
  },
  {
    ingredient: "Oats (King Arthur Rolled)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Oats (old-fashioned or quick-cooking)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.125,
    gram: 89,
  },
  {
    ingredient: "Oats (prepared)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.125,
    gram: 147,
  },
  {
    ingredient: "Olive oil",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.75,
    gram: 50,
  },
  {
    ingredient: "Olives (sliced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Onions (fresh, diced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Paleo Baking Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.625,
    gram: 104,
  },
  {
    ingredient: "Palm shortening",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.5,
    gram: 45,
  },
  {
    ingredient: "Passion fruit purée",
    volume: "1/3 cup",
    volumeRaw: 0.3333333333333333,
    volumeUnit: "cup",
    ounce: 2.125,
    gram: 60,
  },
  {
    ingredient: "Pasta Flour Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.125,
    gram: 145,
  },
  {
    ingredient: "Pastry Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 106,
  },
  {
    ingredient: "Pastry Flour Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Peaches (peeled and diced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Peanut butter",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4.75,
    gram: 135,
  },
  {
    ingredient: "Peanuts (whole, shelled)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Pears (peeled and diced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.75,
    gram: 163,
  },
  {
    ingredient: "Pecan Meal",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 2.75,
    gram: 80,
  },
  {
    ingredient: "Pecans (diced)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Pecans (whole)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 105,
  },
  {
    ingredient: "Pie Filling Enhancer",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.625,
    gram: 46,
  },
  {
    ingredient: "Pine nuts",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 71,
  },
  {
    ingredient: "Pineapple (crushed, drained)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 9,
    gram: 256,
  },
  {
    ingredient: "Pineapple (dried)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 71,
  },
  {
    ingredient: "Pineapple (fresh or canned, diced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Pistachio nuts (shelled)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.125,
    gram: 60,
  },
  {
    ingredient: "Pistachio Paste",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 2.75,
    gram: 78,
  },
  {
    ingredient: "Pizza Dough Flavor",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.4,
    gram: 12,
  },
  {
    ingredient: "Pizza Flour Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.375,
    gram: 124,
  },
  {
    ingredient: "Pizza sauce",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Pizza Seasoning",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.3333333333333333,
    gram: 10,
  },
  {
    ingredient: "Polenta (coarse ground cornmeal)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.75,
    gram: 163,
  },
  {
    ingredient: "Poppy seeds",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.625,
    gram: 18,
  },
  {
    ingredient: "Potato Flour",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.625,
    gram: 46,
  },
  {
    ingredient: "Potato starch",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.375,
    gram: 152,
  },
  {
    ingredient: "Pumpernickel Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 106,
  },
  {
    ingredient: "Pumpkin purée",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Pumpkin seeds",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.375,
    gram: 40,
  },
  {
    ingredient: "Queso fresco",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Quinoa (cooked)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6.5,
    gram: 184,
  },
  {
    ingredient: "Quinoa (whole)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6.25,
    gram: 177,
  },
  {
    ingredient: "Quinoa flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.875,
    gram: 110,
  },
  {
    ingredient: "Raisins (loose)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.25,
    gram: 149,
  },
  {
    ingredient: "Raisins (packed)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 3,
    gram: 85,
  },
  {
    ingredient: "Raspberries (fresh)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: 'Rhubarb (sliced, 1/2" slices)',
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: [4.25, 5],
    gram: [120, 140],
  },
  {
    ingredient: "Rice (long grain, dry)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 3.5,
    gram: 99,
  },
  {
    ingredient: "Rice flour (white)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5,
    gram: 142,
  },
  {
    ingredient: "Rice Krispies",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "Rye Bread Improver",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.5,
    gram: 14,
  },
  {
    ingredient: "Rye Chops",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Rye flakes",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.375,
    gram: 124,
  },
  {
    ingredient: "Rye Flour Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 106,
  },
  {
    ingredient: "Salt (Kosher, Diamond Crystal)",
    volume: "1 tablespoon",
    volumeRaw: 1,
    volumeUnit: "tablespoon",
    ounce: 0.25,
    gram: 8,
  },
  {
    ingredient: "Salt (Kosher, Morton's)",
    volume: "1 tablespoon",
    volumeRaw: 1,
    volumeUnit: "tablespoon",
    ounce: 0.5,
    gram: 16,
  },
  {
    ingredient: "Salt (table)",
    volume: "1 tablespoon",
    volumeRaw: 1,
    volumeUnit: "tablespoon",
    ounce: 0.6666666666666666,
    gram: 18,
  },
  {
    ingredient: "Scallions (sliced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 2.25,
    gram: 64,
  },
  {
    ingredient: "Self-Rising Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Semolina Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.75,
    gram: 163,
  },
  {
    ingredient: "Sesame seeds",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 71,
  },
  {
    ingredient: "Shallots (peeled and sliced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.5,
    gram: 156,
  },
  {
    ingredient: "Six-Grain Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.5,
    gram: 128,
  },
  {
    ingredient: "Snow White Non-Melting Topping Sugar",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Sorghum flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.875,
    gram: 138,
  },
  {
    ingredient: "Sour cream",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Sourdough starter",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: [8, 8.5],
    gram: [227, 241],
  },
  {
    ingredient: "Soy flour",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.25,
    gram: 35,
  },
  {
    ingredient: "Sparkling Sugar",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 2,
    gram: 57,
  },
  {
    ingredient: "Spelt Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.5,
    gram: 99,
  },
  {
    ingredient: "Sprouted Wheat Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Steel cut oats",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.5,
    gram: 70,
  },
  {
    ingredient: "Sticky Bun Sugar",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.5,
    gram: 99,
  },
  {
    ingredient: "Strawberries (fresh sliced)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.875,
    gram: 167,
  },
  {
    ingredient: "Sugar (granulated white)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 7,
    gram: 198,
  },
  {
    ingredient: "Sugar substitute (Splenda)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 0.875,
    gram: 25,
  },
  {
    ingredient: "Sundried tomatoes (dry pack)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "Sunflower seeds",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.25,
    gram: 35,
  },
  {
    ingredient: "Super 10 Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 106,
  },
  {
    ingredient: "Swedish Pearl Sugar",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.75,
    gram: 49,
  },
  {
    ingredient: "Sweetened condensed coconut milk",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 10.125,
    gram: 288,
  },
  {
    ingredient: "Sweetened condensed milk",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 2.75,
    gram: 78,
  },
  {
    ingredient: "Tahini paste",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 4.5,
    gram: 128,
  },
  {
    ingredient: "Tapioca (quick cooking)",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.75,
    gram: 21,
  },
  {
    ingredient: "Tapioca starch or flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Teff flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.75,
    gram: 135,
  },
  {
    ingredient: "The Works Bread Topping",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.25,
    gram: 35,
  },
  {
    ingredient: "Toasted Almond Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.375,
    gram: 96,
  },
  {
    ingredient: "Toffee chunks",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 5.5,
    gram: 156,
  },
  {
    ingredient: "Tomato paste",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 1,
    gram: 29,
  },
  {
    ingredient: "Tropical Fruit Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: [4.5, 5],
    gram: [128, 142],
  },
  {
    ingredient: "Turbinado sugar (raw)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6.375,
    gram: 180,
  },
  {
    ingredient: "Unbleached Cake Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.25,
    gram: 120,
  },
  {
    ingredient: "Vanilla Extract",
    volume: "1 tablespoon",
    volumeRaw: 1,
    volumeUnit: "tablespoon",
    ounce: 0.5,
    gram: 14,
  },
  {
    ingredient: "Vegetable oil",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 7,
    gram: 198,
  },
  {
    ingredient: "Vegetable shortening",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1.625,
    gram: 46,
  },
  {
    ingredient: "Vital Wheat Gluten",
    volume: "2 tablespoons",
    volumeRaw: 2,
    volumeUnit: "tablespoons",
    ounce: 0.625,
    gram: 18,
  },
  {
    ingredient: "Walnuts (chopped)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Walnuts (whole)",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 2.25,
    gram: 64,
  },
  {
    ingredient: "Water",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Wheat berries (red)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6.5,
    gram: 184,
  },
  {
    ingredient: "Wheat bran",
    volume: "1/2 cup",
    volumeRaw: 0.5,
    volumeUnit: "cup",
    ounce: 1.125,
    gram: 32,
  },
  {
    ingredient: "Wheat germ",
    volume: "1/4 cup",
    volumeRaw: 0.25,
    volumeUnit: "cup",
    ounce: 1,
    gram: 28,
  },
  {
    ingredient: "White Chocolate Chips",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 6,
    gram: 170,
  },
  {
    ingredient: "White Rye Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.75,
    gram: 106,
  },
  {
    ingredient: "Whole Grain Flour Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Whole Wheat Flour (Premium 100%)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4,
    gram: 113,
  },
  {
    ingredient: "Whole Wheat Pastry Flour / Graham Flour",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 3.375,
    gram: 96,
  },
  {
    ingredient: "Yeast (instant)",
    volume: "2 1/4 teaspoons",
    volumeRaw: 2.25,
    volumeUnit: "teaspoons",
    ounce: 0.25,
    gram: 7,
  },
  {
    ingredient: "Yogurt",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 8,
    gram: 227,
  },
  {
    ingredient: "Yuletide Cheer Fruit Blend",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: 4.5,
    gram: 130,
  },
  {
    ingredient: "Zucchini (shredded)",
    volume: "1 cup",
    volumeRaw: 1,
    volumeUnit: "cup",
    ounce: [4.25, 5.25],
    gram: [121, 150],
  },
];
